jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - 11
        - 10
        - 8
        - 6
      before_install:
        - npm i -g codecov
      script:
        - npm run verify
        - npm run test:ci
      after_success:
        - codecov
      notifications:
        email:
          on_success: never
          on_failure: always
    - stage: deploy
      branches:
        only:
          - master
      language: node_js
      node_js: 10
      install: true
      before_script:
        - chmod +x publish-website.sh
      script:
        - ./publish-website.sh
      notifications:
        email:
          on_success: never
          on_failure: always
